### ISSUE TITLE
I'm using this on my personal project it's exatcly what I was looking for, except the issue to authenticate without changing the laravel attempt method remains, anybody got a way to authenticate or make searches?

### ISSUE THREAD

**Issue by ricksonoliveira** [betterapp/laravel-db-encrypter#12]

**Comment by iec989** [comment]
I face the same issue @betterapp , when using Laravel default auth's login it doesn't authenticate - what would be the best workaround?

**Comment by betterapp** [comment]
Which db field from user was set up as encrypted ?

**Comment by betterapp** [comment]
Encrypt database field should not be used on laravel authentication fields
