### ISSUE TITLE
Encrypted Column not working in where clause and aggregation functions

### ISSUE THREAD

**Issue by Waqaralipk** [betterapp/laravel-db-encrypter#26]
I have defined a few of my table columns encryptable in the model which needs to be saved encrypted in DB. It's working fine with insert and select, but whenever I am using that encryptable column in my where clause and aggregate functions it's not working for me. Is there anything that I am missing? Can anyone help, please?

**Comment by betterapp** [comment]
curently it is not posible to search in encrypted value
