### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by nite1984** [betterapp/laravel-db-encrypter#31]
Hi,
Im trying to update to Laravel 9, but when I try to run composer update I get this :

`Problem 1
    - Root composer.json requires betterapp/laravel-db-encrypter dev-master -> satisfiable by betterapp/laravel-db-encrypter[dev-master].
..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).`

Can this be fixed ?

**Comment by seifti** [comment]
Any workaround @nite1984 ?

**Comment by nite1984** [comment]
> Any workaround @nite1984 ?

Technically this package is not needed anymore for Laravel 9, but if you still want to use it for an existing project you can fork the package and change the composer.json to accept laravel 9 ("laravel/framework": "^6.0|^7.0|^8.0|^9.0").

Then in your app's composer.json you have to tell composer to look for the package in your github instead of this one (google how to do it, its a 1-liner).

Good luck

**Comment by seifti** [comment]
> > Any workaround @nite1984 ?
> 
> Technically this package is not needed anymore for Laravel 9, but if you still want to use it for an existing project you can fork the package and change the package.json to accept laravel 9 ("laravel/framework": "^6.0|^7.0|^8.0|^9.0").
> 
> Then in your app's package.json you have to tell npm to look for the package in your github instead of this one (google how to do it, its a 1-liner).
> 
> Good luck

Yeah, I was trying to migrate from this library to Laravel encrypted cast, but I'm getting funny values on existing records: https://stackoverflow.com/questions/72878686/migrate-from-encryption-trait-to-laravel-casts

**Comment by nite1984** [comment]
@seifti Honestly for an existing project\database already encrypted I'd just do the composer.json workaround.
Also, of course in my previous reply I was talking about composer.json, not package.json (and composer not npm) lol

Looking at your stackoverflow question, which Im also interested in, one solution could probably be to write code that saves the currently encrypted columns with plain values (first you should comment the encryptable attribute of your models and any Laravel 9 code).
Then, you'd remove this trait, add the Laravel 9 code, and re-save all the columns that needs encryption.
I'll write this also in that thread.

**Comment by lukebouch** [comment]
@nite1984 I'm running into the same issue.

**Comment by betterapp** [comment]
Added support for laravel 9
