### ISSUE TITLE
should be compatible with Illuminate\Database\Eloquent\Model::getAttribute($key)

### ISSUE THREAD

**Issue by nchishti** [betterapp/laravel-db-encrypter#5]
Hi Guys,

I just want to test this package and I am getting the following error regarind the getAttribute method:

`Declaration of betterapp\LaravelDbEncrypter\Traits\EncryptableDbAttribute::getAttribute(string $key) should be compatible with Illuminate\Database\Eloquent\Model::getAttribute($key)`

Any ideas why?

**Comment by nchishti** [comment]
Removing String from the get attribute method within the EncryptableDbAttribute trait got it to work?

` public function getAttribute(String $key)`

**Comment by betterapp** [comment]
Fixed
