### ISSUE TITLE
Error when class extends from Authenticatable

### ISSUE THREAD

**Issue by mikecobb-io** [betterapp/laravel-db-encrypter#6]
My User class extends from Authenticatable ,not Model and I get the following error when I try to use the User class:

`Declaration of betterapp\LaravelDbEncrypter\Traits\EncryptableDbAttribute::getAttribute(string $key) should be compatible with Illuminate\Database\Eloquent\Model::getAttribute($key)`

Any thoughts on how to work round this?
Thanks

**Comment by betterapp** [comment]
This is fixed now. Update package
