### ISSUE TITLE
decrypt() must be of the type string, null returned

### ISSUE THREAD

**Issue by mariomarquesdev** [betterapp/laravel-db-encrypter#8]
I would like to use my 'notes' field with the encryption, but sometimes it can be null, when is not null i would like to encrypt it, using this approach i always must return a string and not null.

protected $encryptable = [
      'name'
       'notes',
 ];

**Comment by monsterdream** [comment]
Agree, have that same problem.

**Comment by betterapp** [comment]
Fixed
